name = "begin"
license = "MIT"
licenselink = "https://github.com/ryanpxx/begin/blob/master/LICENSE.md"
description = "Bootstrap3 based theme for Hugo."
homepage = "https://github.com/ryanpxx/begin"
tags = ["blog"]
features = ["responsive", "thumbnail", "syntax highlight", "structured data", "ogp", "twitter cards"]
min_version = 0.42.2

[author]
  name = "Daisuke Tsuji"


